spring:
  config:
    import: file:${GROND_CONFIG_PATH}
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true

server:
  port: ${services.object-store.port}
  servlet:
    context-path: ${services.object-store.base-path}